/*
 * compliments.js — tek kaynak / single source of truth
 *
 * Bu dosyayı hem site (index.html) hem de e-posta scripti (send_compliment.py)
 * okur. Yeni bir iltifat eklemek için sadece buraya bir satır ekle.
 *
 * Etiketler / tags:
 *   gunluk   — günlük, tatlı, sıradan güzellikler
 *   derin    — derin, şiirsel, ağır sevgi
 *   ozlem    — özlem, mesafe
 *   guc      — zor günler, güç verme, kendine değer
 *   neseli   — şakacı, güldüren
 *   isim     — özel isimler (meri jaan, buggi schnuggi, fettisacki)
 *   gokyuzu  — burç, ay, yıldızlar
 *   biz      — bizim hikâyemiz, anılar
 *
 * ÖNEMLİ: Aşağıdaki dizi geçerli JSON olmalı — yorum satırı ekleme,
 * son elemandan sonra virgül bırakma. Python bunu böyle okuyor.
 */
window.COMPLIMENTS = [
{"t":"Gülüşün odayı aydınlatıyor, tıpkı güneşin sabahı aydınlattığı gibi.","g":["gunluk"]},
{"t":"Sen dünyayı daha güzel bir yer yapıyorsun, sadece var olarak.","g":["gunluk","guc"]},
{"t":"Varlığın tek başına bir armağan — bunu hiç unutma.","g":["derin","guc"]},
{"t":"Gözlerin içindeki güzelliği yansıtıyor; görmek isteyenlere yeter.","g":["derin"]},
{"t":"Seninle geçen her an, hayatımın en değerli anları arasında.","g":["biz"]},
{"t":"Zekân ve güzelliğin mükemmel bir uyum içinde dans ediyor.","g":["gunluk"]},
{"t":"Kalbinin iyiliği seni dünyada eşsiz kılıyor.","g":["derin"]},
{"t":"Seninle olmak cenneti yeryüzünde yaşatıyor.","g":["derin"]},
{"t":"Sesinin tonu beni her seferinde büyülüyor.","g":["gunluk"]},
{"t":"Sen her bakışta biraz daha güzelleşiyorsun.","g":["gunluk"]},
{"t":"Düşünce biçimin beni her zaman hayrete düşürüyor.","g":["guc"]},
{"t":"Seninle gülmek dünyanın en güzel sesi.","g":["neseli","biz"]},
{"t":"Sen olmasan bu dünya ne kadar eksik kalırdı.","g":["derin"]},
{"t":"Güçlü ve nazik olmayı bir arada başarmak için seçilmiş gibisin.","g":["guc"]},
{"t":"Her geçen gün seni bir önceki günden daha çok seviyorum.","g":["derin"]},
{"t":"Sen benim en büyük ilham kaynağımsın.","g":["guc"]},
{"t":"Bakışlarında bir dünya var; içinde kaybolmak istiyorum.","g":["derin"]},
{"t":"Seninle geçirdiğim her dakikayı bir hazine gibi saklıyorum içimde.","g":["biz"]},
{"t":"Seni düşündüğümde her şey daha hafif hissettiriyor.","g":["ozlem"]},
{"t":"Hem güçlü hem şefkatli olmayı çok az kişi başarır — sen başarıyorsun.","g":["guc"]},
{"t":"Kahkahanı duymak benim için en değerli armağan.","g":["neseli"]},
{"t":"Sen benim kalbimin en huzurlu köşesisin.","g":["derin"]},
{"t":"Varlığın sadece benim için değil, çevrendeki herkes için bir şans.","g":["guc"]},
{"t":"Seninle baş başa geçirilen her an, ömrümün en değerlisi.","g":["biz"]},
{"t":"Seni sevmek hayatımın en doğru kararı.","g":["derin"]},
{"t":"Sen benim için güneşin doğduğu yönsün.","g":["derin"]},
{"t":"Her halin farklı bir güzellik taşıyor.","g":["gunluk"]},
{"t":"Seninle her şey daha anlamlı hissettiriyor.","g":["derin"]},
{"t":"Hem aklımı hem kalbimi dolduruyorsun.","g":["derin"]},
{"t":"Kibarlığın ve nezaketin seni çok özel yapıyor.","g":["gunluk"]},
{"t":"Seninle olmak, hayatımın en büyük şansı.","g":["biz"]},
{"t":"Sen benim en sevdiğim hikâyesin.","g":["derin"]},
{"t":"Seninle geçen her mevsim renkleniyor ve anlam kazanıyor.","g":["biz"]},
{"t":"Senin varlığın hayatıma anlam katıyor.","g":["derin"]},
{"t":"Her gün seninle biraz daha büyüyorum.","g":["biz"]},
{"t":"Sen benim için çok değerlisin — bunu her zaman bil.","g":["guc"]},
{"t":"Seninle olmak bir rüya, ama gerçeğinden daha güzel.","g":["derin"]},
{"t":"Güzelliğin içten geliyor; bu seni gerçekten eşsiz kılıyor.","g":["gunluk"]},
{"t":"Sen benim dünyamın en güzel köşesisin.","g":["derin"]},
{"t":"Kalbin kadar güzel bir ruh az görülür.","g":["derin"]},
{"t":"Seninle olmak bana tam bir huzur veriyor.","g":["derin"]},
{"t":"Her bakışın kalbimi ısıtıyor, her seferinde.","g":["gunluk"]},
{"t":"Hem akıllı hem zarifsin; ikisini bu kadar güzel taşıyan az.","g":["guc"]},
{"t":"Gözlerin içindeki sonsuz derinliği yansıtıyor.","g":["derin"]},
{"t":"Seni sevmek, nefes almak kadar doğal geliyor bana.","g":["derin"]},
{"t":"Sen benim için her gün yeniden doğan bir mucizesin.","g":["derin"]},
{"t":"Zarif duruşun ve güzel kalbinle gerçekten eşsizsin.","g":["gunluk"]},
{"t":"Her geçen gün sana olan sevgim biraz daha derinleşiyor.","g":["derin"]},
{"t":"Sen hem güçlü hem naifsin — bu birleşim seni eşsiz yapıyor.","g":["guc"]},
{"t":"Sen benim için güneşin ilk ışığı gibisin.","g":["derin"]},
{"t":"Seninle her sabaha uyanmak, hayatımın en büyük lüksü.","g":["biz"]},
{"t":"Seni tanımak, hayatıma en güzel şeyi katmak oldu.","g":["biz"]},
{"t":"Sen her zaman çevreni daha aydınlık bir yere dönüştürüyorsun.","g":["guc"]},
{"t":"Güzelliğin zamanla değil, kalpten geliyor — bu hiç solmaz.","g":["derin"]},
{"t":"Seninle birlikte olmak, her gün küçük bir mucize.","g":["biz"]},
{"t":"Senin gibisi gerçekten az; bunu bilen şanslı.","g":["gunluk"]},
{"t":"Her gülüşünde bir dünya var ve ben o dünyada yaşamak istiyorum.","g":["derin"]},
{"t":"Sen benim için yıldızlardan daha parlaksın.","g":["gokyuzu"]},
{"t":"Seninle geçirilen her anı ömrüm boyunca hatırlayacağım.","g":["biz"]},
{"t":"Sen benim kalbimin en sevdiği şarkısısın.","g":["derin"]},
{"t":"Seni düşündüğümde her şey yerine oturuyor.","g":["ozlem"]},
{"t":"Sana olan sevgim her gün biraz daha büyüyor.","g":["derin"]},
{"t":"Seninle olmak hayatımın en iyi kararı — her gün bunu hissediyorum.","g":["biz"]},
{"t":"Sen benim için hem sığınak hem macera.","g":["derin"]},
{"t":"Kırşehir seni doğurmuş, dünya sana şükretmeli.","g":["neseli","gunluk"]},
{"t":"Meri jaan, sen benim canım, ruhum, her şeyimsin — bunu her zaman bil.","g":["isim","derin"]},
{"t":"Mein fettisacki, ne kadar tatlı ve eşsiz birisin — kelimeler yetmiyor.","g":["isim","neseli"]},
{"t":"Sevgili buggi schnuggi'm, seninle her gün yeni bir mucize başlıyor.","g":["isim"]},
{"t":"Meri jaan — bu kelime tam seni anlatıyor; sen gerçekten benim canımsın.","g":["isim","derin"]},
{"t":"Her sabah gözlerini açtığında bil ki, buggi schnuggi'm, biri seni çok seviyor.","g":["isim","gunluk"]},
{"t":"Meri jaan, seni sevmek hayatımın en güzel görevi.","g":["isim","derin"]},
{"t":"Mein fettisacki, seninle olmak benim için dünyanın en büyük lüksü.","g":["isim"]},
{"t":"Buggi schnuggi'm, seninle paylaşılan kahkahalar benim en sevdiğim müzik.","g":["isim","neseli"]},
{"t":"Meri jaan, seninle her adım daha anlamlı.","g":["isim"]},
{"t":"Mein fettisacki, sen benim için dünyanın en tatlı sırrısın.","g":["isim","neseli"]},
{"t":"Meri jaan — seninle geçirilen her an, ömrümün en güzel sayfaları.","g":["isim","biz"]},
{"t":"Buggi schnuggi'm, seninle paylaşılan her an hazineye dönüşüyor.","g":["isim","biz"]},
{"t":"Mein fettisacki, seninle her gün yeni bir maceraya atılmak istiyorum.","g":["isim","biz"]},
{"t":"Seninle olmak, en güzel kitabı sonuna kadar okumak gibi — bitmesini istemiyorum.","g":["derin"]},
{"t":"Sen benim için hem liman hem ufuksun.","g":["derin"]},
{"t":"Seni sevmek bir seçim değil, bir ihtiyaç — o kadar doğal.","g":["derin"]},
{"t":"Her sabah seni düşünerek uyanmak, günün en güzel başlangıcı.","g":["gunluk"]},
{"t":"Seninle paylaşılan sessizlik bile anlamlı.","g":["derin","biz"]},
{"t":"Sen benim için kelimelerden büyüksün.","g":["derin"]},
{"t":"Her halinle büyüleyicisin — sevinçli, düşünceli, hatta hüzünlüyken bile.","g":["guc"]},
{"t":"Seni sevmek, en güzel şiiri ezbere bilmek gibi — asla unutmuyorum.","g":["derin"]},
{"t":"Seninle olmak, en güzel melodiyi her gün yeniden duymak gibi.","g":["derin"]},
{"t":"Gözlerindeki ışık hiç sönmüyor — bu seni eşsiz yapıyor.","g":["guc"]},
{"t":"Seni sevmek kolayın kolayı — doğal, saf ve sonsuz.","g":["derin"]},
{"t":"Seninle olmak, hayatımın en doğru cümlesi.","g":["derin"]},
{"t":"Sen benim kalbimin en sık ziyaret ettiği yersin.","g":["derin"]},
{"t":"Seninle olan her hatıra içimi ısıtıyor.","g":["biz"]},
{"t":"Seni sevmek, hayatımın en büyük onuru.","g":["derin"]},
{"t":"Yengeç burcusun — kalbinin derinliği ve sezgilerinin gücü seni özel kılıyor.","g":["gokyuzu"]},
{"t":"Ay'ın çocuğusun; tıpkı Ay gibi her hâlinle büyüleyicisin.","g":["gokyuzu"]},
{"t":"Ejderha yılında doğmuşsun — o güç, cesaret ve büyü sende hep hissedilir.","g":["gokyuzu","guc"]},
{"t":"Su elementi sana o derin sezgiyi vermiş; duyguları bu kadar güzel taşımak bir hediye.","g":["gokyuzu"]},
{"t":"Doğduğun gün dünya çok güzel bir hediye aldı — seni.","g":["gokyuzu"]},
{"t":"Ay seni yönetiyor; bu yüzden hem derinsin hem sırlısın hem de büyüleyici.","g":["gokyuzu"]},
{"t":"Hem cesur hem de şefkatlisin — bu ikisi bir arada az görülür.","g":["guc"]},
{"t":"Güçlü bir kalbin var — hem kendini hem de sevdiklerini koruyorsun.","g":["guc"]},
{"t":"Sevgin her şeyi iyileştiriyor — bu nadir görülen bir güç.","g":["guc"]},
{"t":"Sen içten dışa, her açıdan güzelsin.","g":["gunluk"]},
{"t":"Seninle olmak beni daha iyi bir insan yapıyor.","g":["biz"]},
{"t":"Seni düşünmek bile yüzümde gülümseme açıyor.","g":["ozlem"]},
{"t":"Varlığın güneşin olmadığı günlerde bile sıcak hissettiriyor.","g":["guc"]},
{"t":"Sana olan sevgim her geçen günle kökleniyor, derinleşiyor.","g":["derin"]},
{"t":"Seninle geçirilen her gün bir armağan gibi hissettiriyor.","g":["biz"]},
{"t":"Sana baktığımda dünyanın en güzel tablosunu görüyorum.","g":["gunluk"]},
{"t":"Seninle olmak beni her gün daha mutlu ediyor.","g":["biz"]},
{"t":"Seninle olmak, en güzel rüyayı gerçek gibi yaşamak.","g":["derin"]},
{"t":"Sen benim için her günün en güzel sebebisin.","g":["gunluk"]},
{"t":"Her gün biraz daha sana hayran kalıyorum.","g":["derin"]},
{"t":"Seninle her anı doyasıya yaşamak istiyorum.","g":["biz"]},
{"t":"Her sabah gözlerimi açtığımda seninle aynı dünyada olduğum için şükrediyorum.","g":["derin"]},
{"t":"Sen benim için yıldızlardan da güzel, güneşten de sıcaksın.","g":["gokyuzu"]},
{"t":"Sen benim için hem geçmiş hem gelecek — her şeyimsin.","g":["derin"]},
{"t":"Senin varlığın bana güç veriyor, dayanma gücü.","g":["guc"]},
{"t":"Sen benim için hem ışık hem yönsün.","g":["derin"]},
{"t":"Seninle geçirilen her an, hayatımın en güzel anısı olmaya aday.","g":["biz"]},
{"t":"Sen benim için bir evren — keşfetmeye doyamıyorum.","g":["derin"]},
{"t":"Seni sevmek, dünyanın en doğal şeyi.","g":["derin"]},
{"t":"Sen benim için kelimelerle anlatılamayan bir güzelliksin.","g":["derin"]},
{"t":"Sen benim için hem sabah hem akşam — günümün tamamısın.","g":["derin"]},
{"t":"Seninle olmak, hayatımın en güzel sayfası.","g":["biz"]},
{"t":"Meri jaan, seninle her şey daha büyük, daha derin, daha güzel.","g":["isim","derin"]},
{"t":"Buggi schnuggi'm, sen benim için dünyanın en güzel sürprizisin.","g":["isim"]},
{"t":"Sen benim için sonsuzsun — seni anlatacak kelimeler henüz icat edilmedi.","g":["derin"]},
{"t":"Seninle her sabaha bakmak, hayatımın en büyük ödülü.","g":["biz"]},
{"t":"Mein fettisacki, seninle paylaşılan sessizlik bile bir şiir.","g":["isim","derin"]},
{"t":"Meri jaan, sen olmadan hiçbir şey tam olmazdı.","g":["isim","derin"]},
{"t":"Bugün de dünya senin sabahınla başladı; haberin olsun.","g":["gunluk"]},
{"t":"Sabah kahvesinin kokusu bile senin yanında daha güzel.","g":["gunluk"]},
{"t":"Telefonum titrediğinde ilk aklıma gelen hep sensin.","g":["gunluk","ozlem"]},
{"t":"Yorgun olduğun günlerde bile gözlerin gülüyor.","g":["guc"]},
{"t":"Saçını topladığın o hâline ayrı bir hayranım.","g":["gunluk"]},
{"t":"Bir şeyi anlatırken ellerini nasıl kullandığını izlemeye bayılıyorum.","g":["gunluk"]},
{"t":"En sevdiğim koku, senin boynunun kokusu.","g":["ozlem"]},
{"t":"Sabahları saçın dağınıkken en güzel hâlindesin.","g":["gunluk"]},
{"t":"Kızdığında bile sevimlisin; bunu bilmeni istemezdim ama artık biliyorsun.","g":["neseli"]},
{"t":"Mırıldandığın şarkıları ezberledim, farkında bile değilsin.","g":["gunluk","neseli"]},
{"t":"Sen odaya girdiğinde havanın değiştiğini herkes fark ediyor.","g":["gunluk"]},
{"t":"Bugün ne giydiysen yakışmıştır; bundan hiç şüphem yok.","g":["gunluk","neseli"]},
{"t":"Uykulu sesin dünyanın en güzel alarmı.","g":["gunluk"]},
{"t":"Bir bardak çay bile senin elinden içilince başka oluyor.","g":["gunluk"]},
{"t":"Kitap okurken kaşlarını çatman... o hâlini çok seviyorum.","g":["gunluk"]},
{"t":"Gülerken burnunu kırıştırıyorsun ve o an kalbim duruyor.","g":["gunluk"]},
{"t":"Sen iyi geceler dediğinde gün gerçekten bitiyor.","g":["gunluk"]},
{"t":"Aynaya baktığında benim gördüğümü görebilsen keşke.","g":["guc"]},
{"t":"Bugün de çok güzelsin — dün de öyleydin, yarın da öyle olacaksın.","g":["gunluk"]},
{"t":"Seni özlemek, şehri seninle dolu hayal etmek demek.","g":["ozlem"]},
{"t":"Aramızdaki mesafe kilometrelerle ölçülüyor ama kalp öyle saymıyor.","g":["ozlem"]},
{"t":"Bugün seni fena özledim; bunu bilesin diye yazıyorum.","g":["ozlem"]},
{"t":"Yastığın yanındaki boşluk hep senin adını taşıyor.","g":["ozlem"]},
{"t":"Sesini duymadığım günler eksik geçiyor.","g":["ozlem"]},
{"t":"Ne kadar uzakta olursan ol, her sabah seni düşünerek uyanıyorum.","g":["ozlem"]},
{"t":"Seni özlemek bile güzel — çünkü sen varsın.","g":["ozlem"]},
{"t":"Kalabalıkta seni arıyorum, oysa yanımda olmadığını biliyorum.","g":["ozlem"]},
{"t":"Bir gün daha geçti; sana bir gün daha yaklaştım.","g":["ozlem"]},
{"t":"Kollarımı açtığımda tam sana göre bir boşluk kalıyor.","g":["ozlem"]},
{"t":"En sevdiğim yer neresi diye sorsalar, senin omzun derim.","g":["ozlem","derin"]},
{"t":"Seni düşünmediğim bir saatim yok; itiraf ediyorum.","g":["ozlem"]},
{"t":"Bugün zor geldiyse bil ki bu geçecek ve sen hâlâ ayaktasın.","g":["guc"]},
{"t":"Kendine bu kadar yüklenme; sen zaten fazlasıyla yeterlisin.","g":["guc"]},
{"t":"Her şeyi tek başına taşımak zorunda değilsin — bir kısmını bana bırak.","g":["guc"]},
{"t":"Yorulmana izin var. Güçlü olmak hiç durmamak demek değil.","g":["guc"]},
{"t":"Bugün hiçbir şey yapamadıysan bile sen yine değerlisin.","g":["guc"]},
{"t":"Senin dayanıklılığın beni her seferinde şaşırtıyor.","g":["guc"]},
{"t":"Kendini küçük gördüğün anlarda bile kocamansın.","g":["guc"]},
{"t":"Kimse senin kadar sessizce güçlü olamıyor.","g":["guc"]},
{"t":"Bir gün kötü geçtiyse hayat kötü demek değil; sadece o gün öyleydi.","g":["guc"]},
{"t":"Ağlamak da güçlü olmanın bir parçası; sakın utanma.","g":["guc"]},
{"t":"Kırıldığın yerlerden altınla onarılmış bir seramik gibisin — daha da değerli.","g":["guc","derin"]},
{"t":"Hayatın sana ağır gelen kısmını birlikte hafifletiriz.","g":["guc","biz"]},
{"t":"Sen sandığından çok daha fazlasını başardın.","g":["guc"]},
{"t":"İçindeki o ses seni eleştirdiğinde benim sesimi hatırla: seninle gurur duyuyorum.","g":["guc"]},
{"t":"Bugün sadece nefes almak bile yeterli bir başarı.","g":["guc"]},
{"t":"Zor günlerde bile kimseye kırıcı olmuyorsun; bu çok nadir bir şey.","g":["guc"]},
{"t":"Bilimsel olarak kanıtlandı: dünyanın en tatlı insanı sensin. Kaynak: ben.","g":["neseli"]},
{"t":"Kalbimin şifresini bilseydin, senin doğum günün olduğunu görürdün.","g":["neseli"]},
{"t":"Seni ne kadar sevdiğimi anlatmaya internetim yetmiyor.","g":["neseli"]},
{"t":"Uyanınca ilk düşündüğüm sensin — kahveden bile önce, bu ciddi bir mesele.","g":["neseli","gunluk"]},
{"t":"Uyurken battaniyeyi çalıyorsun ama yine de hep seni seçerim.","g":["neseli","biz"]},
{"t":"Sen olmasan hayat resmen jenerik bir film olurdu.","g":["neseli"]},
{"t":"Seninle tartışmayı bile seviyorum, çünkü sonunda barışmak var.","g":["neseli","biz"]},
{"t":"Buggi schnuggi'm, bugün de dünya rekoru kırdın: en tatlı insan.","g":["neseli","isim"]},
{"t":"Sana bakarken zaman kaybediyorum diyorlar; ben buna yatırım diyorum.","g":["neseli"]},
{"t":"Gülüşünün patenti olsaydı iflas ederdim.","g":["neseli"]},
{"t":"Fotoğraflarının arşivini yapıyorum; neredeyse kütüphane açacağız.","g":["neseli"]},
{"t":"Seninle market alışverişi bile romantik komedi sahnesine dönüşüyor.","g":["neseli","biz"]},
{"t":"Sana kızmayı denedim; on dakika dayanabildim.","g":["neseli"]},
{"t":"Seni sevmek, bildiğim en sade ve en büyük şey.","g":["derin"]},
{"t":"Kalbimde senin adına ayrılmış bir oda var; kapısı hiç kapanmıyor.","g":["derin"]},
{"t":"Bazı insanlar ev arar; ben evimi sende buldum.","g":["derin"]},
{"t":"Seninle kurduğumuz sessizlik, başkasıyla kurduğum konuşmadan derin.","g":["derin","biz"]},
{"t":"Sen benim en güzel tesadüfüm ve en bilinçli tercihimsin.","g":["derin"]},
{"t":"İnsan bir kere sevilir derler; ben seni her gün yeniden seviyorum.","g":["derin"]},
{"t":"Yıllar geçse de elini tutmak hâlâ ilk günkü gibi.","g":["derin","biz"]},
{"t":"Sen hikâyemdeki en güzel cümle değil, kitabın tamamısın.","g":["derin"]},
{"t":"Beni olduğum gibi kabul ettiğin için sana ömür boyu minnettarım.","g":["derin","biz"]},
{"t":"Seninle her şey yavaşlıyor; dünyanın hızına ihtiyacım kalmıyor.","g":["derin"]},
{"t":"Seni sevdiğimi anladığım an hayatım ikiye ayrıldı: senden önce ve sonra.","g":["derin"]},
{"t":"Bir gün çok yaşlanacağız ve ben yine bu satırları yazıyor olacağım.","g":["derin","biz"]},
{"t":"Ruhun benim en sevdiğim manzara.","g":["derin"]},
{"t":"Sen benim en sakin limanım ve en cesur yolculuğumsun.","g":["derin"]},
{"t":"Sevginin bir kokusu olsaydı senin gibi kokardı.","g":["derin"]},
{"t":"Seninle geçen zaman kaybolmuyor; birikiyor.","g":["derin","biz"]},
{"t":"Kalbimi sana emanet ettim ve bir kere bile pişman olmadım.","g":["derin"]},
{"t":"Seni sevmek öğrenilecek bir şey değildi; sadece hatırladım.","g":["derin"]},
{"t":"İlk konuştuğumuz günü hatırlıyor musun? Ben her detayını hatırlıyorum.","g":["biz"]},
{"t":"Birlikte yaptığımız en sıradan şeyler en güzel anılarımız oldu.","g":["biz"]},
{"t":"Bizim hikâyemiz kısa değil; daha yeni başlıyor.","g":["biz"]},
{"t":"Bir gün bu günleri anlatacağız ve gülümseyeceğiz.","g":["biz"]},
{"t":"Yaptığımız planların yarısı gerçekleşse bile çok mutlu olacağız.","g":["biz"]},
{"t":"Seninle susmak, başkasıyla konuşmaktan daha iyi.","g":["biz","derin"]},
{"t":"Birlikte geçirdiğimiz her gün, kalbimde bir taş üstüne bir taş.","g":["biz"]},
{"t":"Bizi biz yapan şey, birbirimizi seçmeye devam etmemiz.","g":["biz","derin"]},
{"t":"Kavga ettiğimiz günlerde bile senden vazgeçmek aklıma gelmedi.","g":["biz"]},
{"t":"Bir gün küçük bir mutfak, ikimiz ve sabah kahvesi — tek hayalim bu.","g":["biz"]},
{"t":"Nerede olursak olalım aynı gökyüzünün altındayız.","g":["ozlem","gokyuzu"]},
{"t":"Seninle kurduğumuz dünya, dışarıdaki dünyadan hep daha güzeldi.","g":["biz"]},
{"t":"Meri jaan, bugün de kalbimin en güzel haberi sensin.","g":["isim","gunluk"]},
{"t":"Mein fettisacki, seni sevmek en sevdiğim alışkanlığım.","g":["isim","neseli"]},
{"t":"Buggi schnuggi'm, seni düşünmek bile günümü kurtarıyor.","g":["isim","ozlem"]},
{"t":"Meri jaan, dünya bazen ağır geliyor; ama sen hafifletiyorsun.","g":["isim","guc"]},
{"t":"Mein fettisacki, sen benim en güzel iyi ki'imsin.","g":["isim","derin"]},
{"t":"Buggi schnuggi'm, bir gün seninle bütün şehirleri gezeceğiz.","g":["isim","biz"]},
{"t":"Meri jaan, kalbim seni her seferinde yeniden seçiyor.","g":["isim","derin"]},
{"t":"Mein fettisacki, sen gülünce benim de günüm gülüyor.","g":["isim","neseli"]},
{"t":"Yengeç burcunun en güzel özelliği sadakat; sende fazlasıyla var.","g":["gokyuzu"]},
{"t":"Ay bu gece de senin için doğdu, haberin olsun.","g":["gokyuzu"]},
{"t":"Ejderha yılının çocuğu — hem asil hem cesur, tam sen.","g":["gokyuzu","guc"]},
{"t":"Yıldızlar bile senin doğduğun günü kutlamak için dizilmiş.","g":["gokyuzu"]},
{"t":"Su burçları derindir derler; sen okyanussun.","g":["gokyuzu"]},
{"t":"Dolunayda daha da güzelleşiyorsun; bilimsel değil ama gerçek.","g":["gokyuzu","neseli"]},
{"t":"Gökyüzüne baktığımda hep seni arıyorum; en parlak olan sensin.","g":["gokyuzu","ozlem"]},
{"t":"Kırşehir'in üstündeki gökyüzü seni büyüttüğü için şanslı.","g":["gokyuzu"]},
{"t":"Bugün kendine iyi davran; senden bir tane var.","g":["guc"]},
{"t":"Bunu sabah okuyorsan: seni seviyorum, günün güzel geçsin.","g":["gunluk"]},
{"t":"Bugün sana bakan herkes şanslı.","g":["gunluk"]},
{"t":"Senin iyiliğin dünyayı gerçekten değiştiriyor, farkında bile değilsin.","g":["guc"]},
{"t":"Bir insanın bu kadar hem tatlı hem akıllı olması haksızlık.","g":["neseli"]},
{"t":"Seninle konuşurken saatlerin nasıl geçtiğini anlamıyorum.","g":["biz"]},
{"t":"Bana anlattığın hayaller benim de hayalim oldu.","g":["biz"]},
{"t":"Merakın ve öğrenme isteğin beni çok etkiliyor.","g":["guc"]},
{"t":"Kendi ayaklarının üzerinde durman beni gururlandırıyor.","g":["guc"]},
{"t":"Bir işi yapmaya karar verdiğinde olacağını biliyorum.","g":["guc"]},
{"t":"İnsanları dinleyişin çok özel; herkes bunu yapamıyor.","g":["guc"]},
{"t":"Küçük şeylere sevinmen hayatın en güzel yanı.","g":["gunluk"]},
{"t":"İyi ki tanışmışız dediğin gün kalbim yerinden çıkacaktı.","g":["biz"]},
{"t":"Sen benim en güzel rutinim ve en güzel sürprizimsin.","g":["derin"]},
{"t":"Bugün de var olduğun için teşekkür ederim.","g":["gunluk","derin"]},
{"t":"Hayatımın en güzel bölümü, seninle tanıştıktan sonrası.","g":["biz","derin"]}
];
